export const canvas = '#universe-canvas'
export const search = '#main-search'
export const searchResultList = '#search-result-list'
export const canvasHtmlPanel = '#html-panel'
export const episodeDescription = '[data-testid="episode-description"]'
