export const openChartBtn = '#cy-open-sentiment-data'
export const chartWrapper = '#cy-sentiment-chart-wrapper'
export const sentimentChart = '#cy-sentiment-chart'
export const sentimentTab = '#sentiment'
export const sentimentSlider = '#cy-sentiment-analysis-slider'
export const requestAnalysBtn = '#cy-get-sentiment-analysis-btn'
export const requestSentimentsBtn = '#cy-get-sentiments-btn'
