name: Docker Build and Push to DockerHub
env:
  DOCKER_CLI_EXPERIMENTAL: enabled

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04
    name: Build and push sphinx-nav-fiber image
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
      - name: Check out from Git
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Setup Docker buildx action
        uses: crazy-max/ghaction-docker-buildx@v1
        id: buildx
        with:
          buildx-version: latest
          qemu-version: latest
      - name: Show available buildx platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Cache Docker layers
        uses: actions/cache@v3
        id: cache
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Run Docker buildx
        run: |
          docker buildx build \
          --cache-to "type=local,dest=/tmp/.buildx-cache" \
          --platform linux/amd64 \
          --tag "${{ secrets.DOCKER_HUB_USER }}/sphinx-nav-fiber:master" \
          --output "type=registry" ./
