name: Nav Fiber - Auto Sync

on:
  push:
    branches:
      - master
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Call Swarm Sync Endpoint
        run: |
          curl -G "https://secondbrain.sphinx.chat/api/git/sync" \
            --data-urlencode "source_link=https://github.com/stakwork/sphinx-nav-fiber,https://github.com/stakwork/jarvis-backend" \
            --data-urlencode "pat=${{ secrets.GITHUB_PAT }}" 
